### ISSUE TITLE
SPDY enabled, chunk fails with 500 error

### ISSUE THREAD

**Issue by Austinb** [vkholodkov/nginx-upload-module#57]
We use this module for uploading larger files into our systems. The module works great over regular SSL mode.  Recently we have been experimenting with SPDY and now that 1.3 is out with nginx 1.5.10 we would like to try to use both.

I have compiled 1.5.10 successfully with SPDY and the upload module.  Again uploads work as expected under both SSL and non-SSL connections.  When SPDY is enabled we see the following error (or a derivation thereof):

```
[alert] 19832#0: *2 epoll_ctl(1, 15) failed (17: File exists), client: 10.0.0.10, server: my.local.server, request: "POST ....
```

This happens for every chunk we try to upload to the server via POST.  The server is running nginx 1.5.10 on CentOS 6.3 that is updated as of this issue.  Using the latest commit from your 2.2 branch.

I did a quick on Google and found something similar but it was related to both ipv4 and v6 being enabled at the same time with SPDY enabled.  Did not help any with this issue.   Please let me know if you need any more information.

**Comment by JoaoCostaImag** [comment]
Had the same error.
Nginx version 1.8 with SPDY enabled.
Disabling it allowed uploads again.

**Comment by Austinb** [comment]
This may be a bogus bug at this point.  SPDY has been removed from 1.9.5 in favor of HTTP/2.  I have not tried using the uploader with HTTP/2 enabled so no idea if it works.  If not I would create a new issue.

**Comment by khavishbhundoo** [comment]
Happens with HTTP/2 as well 
https://github.com/vkholodkov/nginx-upload-module/issues/82

**Comment by Austinb** [comment]
Closing issue since SPDY has been superseded by http/2
