### ISSUE TITLE
Module don't build

### ISSUE THREAD

**Issue by monoflash** [vkholodkov/nginx-upload-module#64]
```
    -o objs/addon/nginx-upload-module-2.1.1/ngx_http_upload_module.o \
    /tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c
```

/tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c: In function ‘ngx_http_upload_merge_loc_conf’:
/tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c:1104:31: error: ‘ngx_garbage_collector_temp_handler’ undeclared (first use in this function)
/tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c:1104:31: note: each undeclared identifier is reported only once for each function it appears in
/tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c:1104:31: error: passing argument 1 of ‘ngx_conf_merge_path_value’ from incompatible pointer type [-Werror]
In file included from src/core/ngx_core.h:58:0,
                 from /tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c:7:
src/core/ngx_file.h:145:7: note: expected ‘struct ngx_conf_t _’ but argument is of type ‘struct ngx_path_t *’
/tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c:1104:31: error: passing argument 2 of ‘ngx_conf_merge_path_value’ from incompatible pointer type [-Werror]
In file included from src/core/ngx_core.h:58:0,
                 from /tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c:7:
src/core/ngx_file.h:145:7: note: expected ‘struct ngx_path_t *_’ but argument is of type ‘struct ngx_path_t _’
/tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c:1104:31: error: passing argument 3 of ‘ngx_conf_merge_path_value’ from incompatible pointer type [-Werror]
In file included from src/core/ngx_core.h:58:0,
                 from /tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c:7:
src/core/ngx_file.h:145:7: note: expected ‘struct ngx_path_t *’ but argument is of type ‘char *’
/tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c:1104:31: error: passing argument 4 of ‘ngx_conf_merge_path_value’ makes pointer from integer without a cast [-Werror]
In file included from src/core/ngx_core.h:58:0,
                 from /tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c:7:
src/core/ngx_file.h:145:7: note: expected ‘struct ngx_path_init_t *’ but argument is of type ‘int’
/tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c:1104:31: error: too many arguments to function ‘ngx_conf_merge_path_value’
In file included from src/core/ngx_core.h:58:0,
                 from /tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c:7:
src/core/ngx_file.h:145:7: note: declared here
/tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c: In function ‘ngx_http_upload_pass_form_field’:
/tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c:1490:5: error: passing argument 1 of ‘ngx_regex_compile’ from incompatible pointer type [-Werror]
In file included from src/core/ngx_core.h:63:0,
                 from /tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c:7:
src/core/ngx_regex.h:50:11: note: expected ‘struct ngx_regex_compile_t *’ but argument is of type ‘struct ngx_str_t *’
/tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c:1490:5: error: too many arguments to function ‘ngx_regex_compile’
In file included from src/core/ngx_core.h:63:0,
                 from /tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c:7:
src/core/ngx_regex.h:50:11: note: declared here
/tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c:1490:14: error: assignment makes pointer from integer without a cast [-Werror]
/tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c:1497:5: error: implicit declaration of function ‘ngx_regex_capture_count’ [-Werror=implicit-function-declaration]
/tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c:1501:28: error: ‘ngx_regex_capture_count_n’ undeclared (first use in this function)
/tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c:1501:54: error: expected ‘)’ before string constant
/tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c: In function ‘ngx_http_read_upload_client_request_body’:
/tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c:1922:7: error: ‘ngx_http_request_body_t’ has no member named ‘to_write’
/tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c: In function ‘ngx_http_do_read_upload_client_request_body’:
/tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c:1991:56: error: ‘ngx_http_request_body_t’ has no member named ‘to_write’
/tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c:1997:19: error: ‘ngx_http_request_body_t’ has no member named ‘to_write’
/tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1/ngx_http_upload_module.c:2063:44: error: ‘ngx_http_request_body_t’ has no member named ‘to_write’
cc1: all warnings being treated as errors
make[1]: *_\* [objs/addon/nginx-upload-module-2.1.1/ngx_http_upload_module.o] Error 1
make[1]: Leaving directory `/tmp/tmp.u9LG3yucM0/nginx-1.7.5'
make: **\* [build] Error 2
# uname -a

Linux vps-core-dev 3.4.63-2.44-desktop #1 SMP PREEMPT Wed Oct 2 11:18:32 UTC 2013 (d91a619) x86_64 x86_64 x86_64 GNU/Linux
# Configure log:

configuring additional modules
adding module in /tmp/tmp.u9LG3yucM0/upload_progress-0.9.0
- ngx_http_uploadprogress_module was configured
  adding module in /tmp/tmp.u9LG3yucM0/nginx-upload-module-2.1.1
- ngx_http_upload_module was configured
  adding module in /tmp/tmp.u9LG3yucM0/nginx-dav-ext-module-0.0.2
- ngx_http_dav_ext_module was configured
  adding module in /tmp/tmp.u9LG3yucM0/nginx-rtmp-module-2014.04.24
- ngx_rtmp_module was configured
  checking for libxslt ... found
  checking for libexslt ... found
  checking for GD library ... found
  checking for perl
- perl version: This is perl 5, version 16, subversion 0 (v5.16.0) built for x86_64-linux-thread-multi
- perl interpreter multiplicity found
  checking for GeoIP library ... found
  checking for Google perftools ... found
  creating objs/Makefile
# Nginx version:

1.7.5

**Comment by gblakeman** [comment]
I keep getting the same error. I've tried with Nginx 1.7.10 and 1.6.2

```
/home/gbhost4/nginx-upload-module/ngx_http_upload_module.c: In function ‘ngx_http_upload_merge_loc_conf’:
/home/gbhost4/nginx-upload-module/ngx_http_upload_module.c:1104:31: error: ‘ngx_garbage_collector_temp_handler’ undeclared (first use in this function)
/home/gbhost4/nginx-upload-module/ngx_http_upload_module.c:1104:31: note: each undeclared identifier is reported only once for each function it appears in
/home/gbhost4/nginx-upload-module/ngx_http_upload_module.c:1104:31: warning: passing argument 1 of ‘ngx_conf_merge_path_value’ from incompatible pointer type [enabled by default]
src/core/ngx_file.h:145:7: note: expected ‘struct ngx_conf_t *’ but argument is of type ‘struct ngx_path_t *’
/home/gbhost4/nginx-upload-module/ngx_http_upload_module.c:1104:31: warning: passing argument 2 of ‘ngx_conf_merge_path_value’ from incompatible pointer type [enabled by default]
src/core/ngx_file.h:145:7: note: expected ‘struct ngx_path_t **’ but argument is of type ‘struct ngx_path_t *’
/home/gbhost4/nginx-upload-module/ngx_http_upload_module.c:1104:31: warning: passing argument 3 of ‘ngx_conf_merge_path_value’ from incompatible pointer type [enabled by default]
src/core/ngx_file.h:145:7: note: expected ‘struct ngx_path_t *’ but argument is of type ‘char *’
/home/gbhost4/nginx-upload-module/ngx_http_upload_module.c:1104:31: warning: passing argument 4 of ‘ngx_conf_merge_path_value’ makes pointer from integer without a cast [enabled by default]
src/core/ngx_file.h:145:7: note: expected ‘struct ngx_path_init_t *’ but argument is of type ‘int’
/home/gbhost4/nginx-upload-module/ngx_http_upload_module.c:1104:31: error: too many arguments to function ‘ngx_conf_merge_path_value’
src/core/ngx_file.h:145:7: note: declared here
/home/gbhost4/nginx-upload-module/ngx_http_upload_module.c: In function ‘ngx_http_upload_pass_form_field’:
/home/gbhost4/nginx-upload-module/ngx_http_upload_module.c:1490:5: warning: passing argument 1 of ‘ngx_regex_compile’ from incompatible pointer type [enabled by default]
src/core/ngx_regex.h:50:11: note: expected ‘struct ngx_regex_compile_t *’ but argument is of type ‘struct ngx_str_t *’
/home/gbhost4/nginx-upload-module/ngx_http_upload_module.c:1490:5: error: too many arguments to function ‘ngx_regex_compile’
src/core/ngx_regex.h:50:11: note: declared here
/home/gbhost4/nginx-upload-module/ngx_http_upload_module.c:1490:14: warning: assignment makes pointer from integer without a cast [enabled by default]
/home/gbhost4/nginx-upload-module/ngx_http_upload_module.c:1497:5: warning: implicit declaration of function ‘ngx_regex_capture_count’ [-Wimplicit-function-declaration]
/home/gbhost4/nginx-upload-module/ngx_http_upload_module.c:1501:28: error: ‘ngx_regex_capture_count_n’ undeclared (first use in this function)
/home/gbhost4/nginx-upload-module/ngx_http_upload_module.c:1501:54: error: expected ‘)’ before string constant
/home/gbhost4/nginx-upload-module/ngx_http_upload_module.c: In function ‘ngx_http_read_upload_client_request_body’:
/home/gbhost4/nginx-upload-module/ngx_http_upload_module.c:1922:7: error: ‘ngx_http_request_body_t’ has no member named ‘to_write’
/home/gbhost4/nginx-upload-module/ngx_http_upload_module.c: In function ‘ngx_http_do_read_upload_client_request_body’:
/home/gbhost4/nginx-upload-module/ngx_http_upload_module.c:1991:56: error: ‘ngx_http_request_body_t’ has no member named ‘to_write’
/home/gbhost4/nginx-upload-module/ngx_http_upload_module.c:1997:19: error: ‘ngx_http_request_body_t’ has no member named ‘to_write’
/home/gbhost4/nginx-upload-module/ngx_http_upload_module.c:2063:44: error: ‘ngx_http_request_body_t’ has no member named ‘to_write’
make[1]: *** [objs/addon/nginx-upload-module/ngx_http_upload_module.o] Error 1
make[1]: Leaving directory `/home/gbhost4/nginx-1.7.10'
make: *** [build] Error 2
```

Ubuntu 12.04.5 using the passenger gem to install.

My configure script:

```
sh ./configure --prefix='/opt/nginx' --with-http_ssl_module --with-http_gzip_static_module --with-http_stub_status_module --with-cc-opt='-Wno-error' --with-pcre='/tmp/passenger.1cl9u17/pcre-8.34' --add-module='/var/lib/gems/1.9.1/gems/passenger-5.0.1/ext/nginx' --add-module='/home/gbhost4/nginx-upload-module'
```

Any tips or ideas?

**Comment by gblakeman** [comment]
Never-mind, this did the trick: https://github.com/vkholodkov/nginx-upload-module/issues/26#issuecomment-6095801
