### ISSUE TITLE
Documentation not available

### ISSUE THREAD

**Issue by petrofcz** [vkholodkov/nginx-upload-module#76]
The resource 

http://www.grid.net.ru/nginx/upload.en.html 

is not available any more

**Comment by bosenok** [comment]
+1

**Comment by Ramel** [comment]
https://web.archive.org/web/20150822114319/http://www.grid.net.ru/nginx/upload.en.html

**Comment by vkholodkov** [comment]
It's available again: http://www.grid.net.ru/nginx/upload.en.html
